import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      < Head >
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
      </Head >
      <main className={styles.main}>
        <div className={styles.imageWrap}>
          <img className={styles.myImg} src="/homeimg.jpg" alt="hunting coder" width={237} height={158} />
        </div>
        <h1 className={styles.title}>
          <span className='mySpan'>&lt;HuntingCoder/&gt;</span>
        </h1>
        <p className={styles.description}>
          A Blog for hunting coders by a Hunting Coder
        </p>
        <div>
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div>
            <h3 className={styles.h3}> How to Learn JavaScript in 2022?</h3>
            <p> Mostly JavaScript used to create a website.</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div>
            <h3 className={styles.h3}> How to Learn JavaScript in 2022?</h3>
            <p className={styles.p}> Mostly JavaScript used to create a website.</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div>
            <h3 className={styles.h3}> How to Learn JavaScript in 2022?</h3>
            <button className={styles.btn}>Read More</button>
            <p> Mostly JavaScript used to create a website.</p>
          </div>
        </div>
      </main>
    </div>
  )
}
